### ISSUE TITLE
Scrollbalken bei ObjektAuswahl / scrollbar at Object lookup

### ISSUE THREAD

**Issue by Bischof-Mak** [jensweigele/ioBroker.yahka#50] opened 2018-04-16 14:38 UTC
Version 0.7.1

![2018-04-16_14h33_09](https://user-images.githubusercontent.com/38432207/38815452-454125a8-4194-11e8-81c4-639af07481e7.png)

Deutsch:
Beim auswählen der Objekte ist kein Scrollbalken vorhanden....

English:
When selecting the objects there is no scrollbar.....

**Comment by jensweigele** [comment] 2018-09-18 19:49
@GermanBluefox : isn't that an issue of the admin adapter?
The tree view is not part of Yahka!?

**Comment by GermanBluefox** [comment] 2018-09-19 06:01
Yes. It is admin issue.

@Bischof-Mak browser? Mac?

**Comment by Bischof-Mak** [comment] 2018-12-05 11:30
> @GermanBluefox / @Bischof-Mak is the problem solved?
> Is there an issue we should reference here?

Hi,
sorry for the late Answer.
I tried it with a completely new system.
npm: 6.4.1
Node: 8.12.0
Nodejs: 8.12.0

I tested it with version 7.1.
and version 8.1

With both versions I had no option to scroll in the list to select the object.

**Comment by jensweigele** [comment] 2018-12-09 11:32
I close this issue here - I think the issue is related to the ioBroker.admin Module. I created a ticket there: https://github.com/ioBroker/ioBroker.admin/issues/337

**Closed by jensweigele** 2018-12-09 11:32 UTC
